source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!


target 'Recruitment' do
  pod 'Alamofire'
  pod 'TPKeyboardAvoiding'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
end